# Generated by Django 4.2 on 2023-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army_no', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('name', models.TextField()),
                ('appointment', models.TextField()),
                ('sub_unit', models.TextField()),
                ('medical_cat', models.TextField(verbose_name='Medical Category')),
                ('age', models.IntegerField()),
            ],
        ),
    ]
